version: '3.8'

services:
  pixl-web:
    build: .
    platform: linux/amd64
    container_name: pixl_server
    restart: always
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
    # 限制容器资源（可选，防止内存溢出导致宿主机宕机）
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
